package com.cotech.taxislibres;

public enum EstadosUnidad {
	PRUEBA_RED,LIBRE, SOLICITUD_TAXI, TAXI_ASIGNADO, ENCUESTA, ESPERA, CANCELADO, ESPERADEPAGO,LLEGO_CARRO,PAGANDO_VALE,CANCELADO_POR_TAXISTA;
		
}
